### PR TITLE
Open Source Contributions for October 

### PR DESCRIPTION
**Pull request by ThePrekshyaGyawali**
Hi, I have added some shell programs as open source contributions.

### CODE REVIEW

**Comment by harsh1x4** [comment]
Have you signed up for Hacktoberfest? If yes, can you please tell me by looking at the Hacktoberfest website that this repository is excluded or non-excluded?

**Comment by ThePrekshyaGyawali** [comment]
Yes, I have signed up for hacktoberfest.

**Comment by harsh1x4** [comment]
Can you please visit the site and check that this repository is excluded or non-excluded.

**Comment by knchapagai** [comment]
It is not excluded !

**Comment by knchapagai** [comment]
@ThePrekshyaGyawali , you are supposed to make 4 PR requests, not one with 4 files,

**Pull request merged**
